hyundai_kroma_brandresource_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: hyundai.controller.brandresource:indexAction
        _sylius:
            template: HyundaiKromaBundle:Frontend/BrandResource:index.html.twig
            paginate: 100
            criteria:
                brand: $brand_id
            
hyundai_kroma_brandresource_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: hyundai.controller.brandresource:createAction
        _sylius:
            template: HyundaiKromaBundle:Frontend/BrandResource:create.html.twig
            redirect:
                route: hyundai_kroma_brandresource_index
                parameters: { brand_id: $brand_id }

hyundai_kroma_brandresource_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: hyundai.controller.brandresource:updateAction
        _sylius:
            template: HyundaiKromaBundle:Frontend/BrandResource:update.html.twig
            redirect: 
                route: hyundai_kroma_brandresource_update
                parameters: { brand_id: $brand_id, id: $id }

hyundai_kroma_brandresource_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: hyundai.controller.brandresource:deleteAction
        _sylius:
            redirect: 
                route: hyundai_kroma_brandresource_index
                parameters: { brand_id: $brand_id }