hyundai_kroma_brand_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: hyundai.controller.brand:indexAction
        _sylius:
            template: HyundaiKromaBundle:Frontend/Brand:index.html.twig
            paginate: 100
            
hyundai_kroma_brand_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: hyundai.controller.brand:createAction
        _sylius:
            template: HyundaiKromaBundle:Frontend/Brand:create.html.twig
            redirect: hyundai_kroma_brand_update

hyundai_kroma_brand_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: hyundai.controller.brand:updateAction
        _sylius:
            template: HyundaiKromaBundle:Frontend/Brand:update.html.twig
            redirect: hyundai_kroma_brand_update

hyundai_kroma_brand_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: hyundai.controller.brand:deleteAction
        _sylius:
            redirect: hyundai_kroma_brand_index