hyundai_kroma_index:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: hyundai_kroma_dashboard
        permanent: true
    
hyundai_kroma_dashboard:
    pattern: /dashboard
    defaults: { _controller: HyundaiKromaBundle:Frontend/Main:dashboard }
        
hyundai_kroma_posts:
    resource: @HyundaiKromaBundle/Resources/config/routing/frontend/post.yml
    prefix: /posts