hyundai_kroma_index:
    pattern: /
    defaults: { _controller: HyundaiKromaBundle:Frontend/Main:redirectIndexUser }
    
hyundai_kroma_dashboard:
    pattern: /dashboard
    defaults: { _controller: HyundaiKromaBundle:Frontend/Main:dashboard }
        
hyundai_kroma_brand:
    resource: @HyundaiKromaBundle/Resources/config/routing/frontend/brand.yml
    prefix: /brands
    
hyundai_kroma_branduser:
    resource: @HyundaiKromaBundle/Resources/config/routing/frontend/branduser.yml
    prefix: /brands_user
    
hyundai_kroma_brandresourcecategory:
    resource: @HyundaiKromaBundle/Resources/config/routing/frontend/brandResourceCategory.yml
    prefix: /category
    
hyundai_kroma_brandresource:
    resource: @HyundaiKromaBundle/Resources/config/routing/frontend/brandResource.yml
    prefix: /resources
    
hyundai_kroma_brandresourcefile:
    resource: @HyundaiKromaBundle/Resources/config/routing/frontend/brandResourceFile.yml
    prefix: /resources/{brandresource_id}/files
                
hyundai_kroma_brandresourcefile_download:
    pattern: /resources/{id}/download
    methods: [GET]
    defaults:
        _controller: hyundai.controller.brandresourcefile:downloadAction
        
hyundai_kroma_brandresourcefile_preview:
    pattern: /file/{id}/preview
    methods: [GET]
    defaults:
        _controller: hyundai.controller.brandresourcefile:previewAction
        
hyundai_kroma_user:
    resource: @HyundaiKromaBundle/Resources/config/routing/frontend/user.yml
    prefix: /user