hyundai_kroma_login:
    pattern:   /login
    defaults:  { _controller: HyundaiKromaBundle:Frontend/Security:login }
    
hyundai_kroma_login_check:
    pattern:   /login_check

hyundai_kroma_logout:
    pattern: /logout
    defaults: { _controller: FosUserBundle:Security:logout }

hyundai_kroma_index:
    pattern:  /
    defaults: { _controller: HyundaiKromaBundle:Frontend/Main:index }
