hyundai_kroma_user_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: hyundai.controller.user:indexAction
        _sylius:
            template: HyundaiKromaBundle:Frontend/User:index.html.twig
            paginate: 100
            
hyundai_kroma_user_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: hyundai.controller.user:createAction
        _sylius:
            template: HyundaiKromaBundle:Frontend/User:create.html.twig
            redirect: hyundai_kroma_user_update

hyundai_kroma_user_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: hyundai.controller.user:updateAction
        _sylius:
            template: HyundaiKromaBundle:Frontend/User:update.html.twig
            redirect: hyundai_kroma_user_update

hyundai_kroma_user_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: hyundai.controller.user:deleteAction
        _sylius:
            redirect: hyundai_kroma_user_index