Hyundai\KromaBundle\Entity\BrandResourceFile:
    type: entity
    table: brand_resource_file
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        resource:
            type: string
            length: 255
            nullable: true
        type:
            type: string
            length: 255
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update
    manyToOne:
        brandResource:
            targetEntity: BrandResource
            inversedBy: files
            joinColumn:
                name: brandresource_id
                referencedColumnName: id
                onDelete: CASCADE