Hyundai\KromaBundle\Entity\User:
    type: entity
    table: fos_user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            column: first_name
            type: string
            length: 255
            nullable: true
        lastName:
            column: last_name
            type: string
            length: 255
            nullable: true
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update
    attributeOverride:     
        password:
            type: string  
            nullable: true
    lifecycleCallbacks: {  }
