gecko_backend:
    resource: "@GeckoBackendBundle/Resources/config/routing/main.yml"
    prefix:   /admin

hyundai_kroma:
    resource: "@HyundaiKromaBundle/Resources/config/routing/main.yml"
    prefix:   /

