gecko_backend_security_login:
    pattern: /login
    methods: [GET]
    defaults:
        _controller: gecko.backend.controller.security:loginAction

gecko_backend_security_login_check:
    pattern: /login-check
    methods: [POST]
    defaults:
        _controller: gecko.backend.controller.security:checkAction

gecko_backend_security_logout:
    pattern: /logout
    methods: [GET]
    defaults:
        _controller: gecko.backend.controller.security:logoutAction
