gecko_backend:
    resource: "@GeckoBackendBundle/Resources/config/routing/main.yml"
    prefix:   /

hyundai_kroma:
    resource: "@HyundaiKromaBundle/Resources/config/routing/main.yml"
    prefix:   /

