security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:    ^/(_profiler|_wdt|css|js)
            security:   false
                                
        main:
            pattern: /.*
            form_login:
                provider: fos_userbundle
                login_path: /login
                check_path: /login_check
                default_target_path: /
                use_referer: true
            logout:
                path: /logout
                target: /login
            anonymous: true
            context:   hyundai
            
    access_control:        
        - { path: ^/media.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/js.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*, role: [ROLE_USER, ROLE_ADMIN] }
