parameters:
#    hyundai_kroma.example.class: Hyundai\KromaBundle\Example

services:
#    hyundai_kroma.example:
#        class: %hyundai_kroma.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
