parameters:
#    hyundai_kroma.example.class: Hyundai\KromaBundle\Example

services:
    hyundai_kroma.frontend.menu_builder:
        class: Hyundai\KromaBundle\Menu\FrontendMenuBuilder
        arguments: ["@knp_menu.factory"]
        
    hyundai_kroma.frontend.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: hyundai_kroma.frontend.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: backend_main_menu } # The alias is what is used to retrieve the menu
            
    hyundai.form.type.post:
        class: Hyundai\KromaBundle\Form\Type\PostType
        tags:
            - { name: form.type, alias: hyundai_post }
            
    hyundai.form.type.user:
        class: Hyundai\KromaBundle\Form\Type\UserType
        tags:
            - { name: form.type, alias: hyundai_user }
