fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#sylius_backend_settings:
#    resource: @SyliusWebBundle/Resources/config/routing/backend/settings.yml
#    prefix: /settings

#gecko_backend_security:
#    resource: @GeckoBackendBundle/Resources/config/routing/security.yml
