gecko_backend_index:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: gecko_backend_dashboard
        permanent: true

gecko_backend_dashboard:
    pattern: /dashboard
    defaults: { _controller: gecko.backend.controller.dashboard:mainAction }

#sylius_backend_settings:
#    resource: @SyliusWebBundle/Resources/config/routing/backend/settings.yml
#    prefix: /settings

gecko_backend_security:
    resource: @GeckoBackendBundle/Resources/config/routing/security.yml
