parameters:
    gecko.backend.controller.dashboard.class: Gecko\BackendBundle\Controller\DashboardController
    gecko.backend.controller.security.class:  Gecko\BackendBundle\Controller\SecurityController

services:
    gecko.backend.controller.dashboard:
        class: %gecko.backend.controller.dashboard.class%
        calls:
            - [setContainer, [@service_container]]

    gecko.backend.controller.security:
        class: %gecko.backend.controller.security.class%
        calls:
            - [setContainer, [@service_container]]